# Generated by Django 3.0.3 on 2020-05-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200501_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-rocket', 'Foguete'), ('ini-layers', 'Camadas'), ('ini-cog', 'Engrenagem'), ('ini-stats-up', 'Design'), ('ini-users', 'Usuários'), ('ini-mobile', 'Mobile')], max_length=12, verbose_name='Ícone'),
        ),
    ]
