# Generated by Django 3.0.3 on 2020-05-01 06:08

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200501_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-mobile', 'Mobile'), ('ini-layers', 'Camadas'), ('ini-users', 'Usuários'), ('ini-cog', 'Engrenagem'), ('ini-stats-up', 'Design'), ('ini-rocket', 'Foguete')], max_length=12, verbose_name='Ícone'),
        ),
    ]
