# Generated by Django 2.2.9 on 2020-08-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200806_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Camadas'), ('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Design'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Ícone'),
        ),
    ]
